# =================== #
name: Holla-01
# =================== #
on:
   workflow_dispatch:
   schedule:
      - cron: "0 * * * *"
# =================== #
jobs:
   Builds-01:
      runs-on: windows-latest
      strategy:
         matrix:
            python-version: [3.9, 3.9, 3.9, 3.9, 3.9]
# =================== #
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Setup Python
           uses: actions/setup-python@v2
           with:
              python-version: 3.9
         - name: Install Dependencies
           run: |
              python -m pip install --upgrade pip
              pip install selenium requests random-text-generator undetected-chromedriver rich random-user-agent
         - name: Mulai
           timeout-minutes: 13
           continue-on-error: True
           run: |
              python main.py
